# Generated by Django 2.0.1 on 2018-05-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testcase_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.IntegerField()),
                ('casename', models.CharField(max_length=150)),
                ('runtime', models.CharField(max_length=150)),
                ('testresult', models.TextField()),
                ('request', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
