# Generated by Django 2.0.1 on 2018-05-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testrun_testserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.CharField(default='fx', max_length=150),
            preserve_default=False,
        ),
    ]
