# Generated by Django 2.0.1 on 2018-06-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testrun_testserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='data_format',
            field=models.CharField(default='form', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='headers',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
