# Generated by Django 2.0.1 on 2018-06-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180606_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.CharField(default='fx', max_length=150),
            preserve_default=False,
        ),
    ]
