# Generated by Django 2.0.1 on 2018-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_testcase_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitename', models.CharField(max_length=150)),
                ('project', models.CharField(max_length=150)),
                ('testresult', models.CharField(max_length=50)),
                ('passnumber', models.IntegerField()),
                ('failnumber', models.IntegerField()),
                ('successrate', models.FloatField()),
                ('runtime', models.DateTimeField()),
            ],
        ),
    ]
