# Generated by Django 2.0.1 on 2018-06-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_testcase_project'),
        ('api', '0007_testsuite'),
    ]

    operations = [
    ]
