# Generated by Django 2.0.1 on 2018-06-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20180606_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='data_format',
            new_name='dataformat',
        ),
    ]
