# Generated by Django 2.0.1 on 2018-06-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180612_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitename', models.CharField(max_length=150)),
                ('project', models.CharField(max_length=150)),
                ('testresult', models.CharField(max_length=50)),
                ('passnumber', models.IntegerField()),
                ('failnumber', models.IntegerField()),
                ('successrate', models.FloatField()),
                ('runtime', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='testsuite',
            old_name='project',
            new_name='projects',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='failnumber',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='passnumber',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='successrate',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='testresult',
        ),
    ]
