# Generated by Django 2.0.1 on 2018-06-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180615_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='caseids',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
