# Generated by Django 2.0.1 on 2018-06-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_testsuite_serverid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='testsuite',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
