# Generated by Django 2.0.1 on 2018-06-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_testrun_testsuite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='expect',
            new_name='expects',
        ),
    ]
