# Generated by Django 2.0.1 on 2018-06-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180622_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='protocol',
            field=models.CharField(default='http', max_length=50),
            preserve_default=False,
        ),
    ]
